// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TecAjalpan.Horarios.Infrastructure.Persistence;

#nullable disable

namespace TecAjalpan.Horarios.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Horarios")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "Seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolesClaims", "Seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsuariosClaims", "Seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UsuariosLogins", "Seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuariosRoles", "Seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsuariosTokens", "Seguridad");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.AjusteManual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SesionHorarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresAnteriores")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNuevos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SesionHorarioId");

                    b.ToTable("AjustesManuales", "Horarios");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Bitacora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Entidad", "RegistroId", "Fecha");

                    b.ToTable("Bitacora", "Auditoria");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("BitacoraHistory", "Auditoria");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.CargaAcademica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OfertaMateriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioAutoriza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("OfertaMateriaId")
                        .IsUnique()
                        .HasFilter("[Eliminado] = 0");

                    b.ToTable("CargasAcademicas", "Operacion");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Carrera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasFilter("[Eliminado] = 0");

                    b.ToTable("Carreras", "Catalogos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.ConfiguracionSabatina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Validada")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId")
                        .IsUnique();

                    b.ToTable("ConfiguracionesSabatinas", "Sabatino");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.ConfiguracionSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorSecundario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DuracionBloqueMinutos")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<byte>("FinEscolarizado")
                        .HasColumnType("tinyint");

                    b.Property<byte>("InicioEscolarizado")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MaximoConsecutivasMateria")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MaximoHorasDocenteDia")
                        .HasColumnType("tinyint");

                    b.Property<string>("NombreInstitucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("RutaLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionSistema", "Configuracion");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.DisponibilidadBloque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Bloque")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Dia")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("DisponibilidadDocenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Preferente")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DisponibilidadDocenteId", "Dia", "Bloque")
                        .IsUnique();

                    b.ToTable("DisponibilidadesBloques", "Recursos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.DisponibilidadDocente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaValidacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioValida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Validada")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("PeriodoId", "DocenteId")
                        .IsUnique();

                    b.ToTable("DisponibilidadesDocentes", "Recursos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.DisponibilidadEspacio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Bloque")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Dia")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<Guid>("EspacioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EspacioId");

                    b.HasIndex("PeriodoId", "EspacioId", "Dia", "Bloque")
                        .IsUnique();

                    b.ToTable("DisponibilidadesEspacios", "Recursos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Docente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("CargaMaximaSemanal")
                        .HasColumnType("tinyint");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<byte>("HorasPermanenciaSemanal")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NumeroTrabajador")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NumeroTrabajador")
                        .IsUnique();

                    b.ToTable("Docentes", "Recursos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.DocenteCarrera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("DocenteId")
                        .IsUnique()
                        .HasFilter("[EsPrincipal] = 1 AND [Eliminado] = 0");

                    b.HasIndex("DocenteId", "CarreraId")
                        .IsUnique()
                        .HasFilter("[Eliminado] = 0");

                    b.ToTable("DocentesCarreras", "Recursos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.JornadaDocente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DisponibilidadDocenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Dia")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DisponibilidadDocenteId", "Dia")
                        .IsUnique()
                        .HasFilter("[Eliminado] = 0");

                    b.ToTable("JornadasDocentes", "Recursos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.EjecucionGenerador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasProgramadas")
                        .HasColumnType("int");

                    b.Property<int>("HorasSolicitadas")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PeriodoCarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TiempoLimiteSegundos")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EjecucionesGenerador", "Horarios");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Espacio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<short?>("Capacidad")
                        .HasColumnType("smallint");

                    b.Property<Guid>("CarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasFilter("[Eliminado] = 0");

                    b.HasIndex("CarreraId", "Clave")
                        .IsUnique();

                    b.ToTable("Espacios", "Catalogos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("PeriodoCarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Semestre")
                        .HasColumnType("tinyint");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoCarreraId", "Clave")
                        .IsUnique();

                    b.ToTable("Grupos", "Academico");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.HorarioVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PeriodoCarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioPublica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoCarreraId");

                    b.HasIndex("PeriodoId", "PeriodoCarreraId")
                        .IsUnique()
                        .HasFilter("[Estado] = 4 AND [Eliminado] = 0");

                    b.HasIndex("PeriodoId", "PeriodoCarreraId", "Numero")
                        .IsUnique()
                        .HasFilter("[PeriodoCarreraId] IS NOT NULL");

                    b.ToTable("HorariosVersiones", "Horarios");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Materia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("Creditos")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<byte>("HorasSemanales")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ReticulaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Semestre")
                        .HasColumnType("tinyint");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasFilter("[Eliminado] = 0");

                    b.HasIndex("ReticulaId");

                    b.ToTable("Materias", "Catalogos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Modalidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasFilter("[Eliminado] = 0");

                    b.ToTable("Modalidades", "Catalogos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5ecb763-fb0a-4a73-a897-fcc648661101"),
                            Activo = true,
                            Clave = "ESC",
                            Eliminado = false,
                            FechaCrea = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Escolarizada",
                            Tipo = (byte)1,
                            UsuarioCrea = "sistema"
                        },
                        new
                        {
                            Id = new Guid("f5ecb763-fb0a-4a73-a897-fcc648661102"),
                            Activo = true,
                            Clave = "SAB",
                            Eliminado = false,
                            FechaCrea = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Sabatina",
                            Tipo = (byte)2,
                            UsuarioCrea = "sistema"
                        });
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.ModuloMateria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModuloSabatinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OfertaMateriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Turno")
                        .HasColumnType("tinyint");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfertaMateriaId");

                    b.HasIndex("ModuloSabatinoId", "OfertaMateriaId")
                        .IsUnique();

                    b.HasIndex("ModuloSabatinoId", "Turno")
                        .IsUnique();

                    b.ToTable("ModulosMaterias", "Sabatino");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.ModuloSabatino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfiguracionSabatinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Semanas")
                        .HasColumnType("tinyint");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionSabatinaId", "Orden")
                        .IsUnique();

                    b.ToTable("ModulosSabatinos", "Sabatino");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.OfertaMateria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("HorasRequeridas")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("GrupoId", "MateriaId")
                        .IsUnique();

                    b.ToTable("OfertasMaterias", "Academico");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.PendienteGeneracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CargaAcademicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HorarioVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("HorasPendientes")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CargaAcademicaId");

                    b.HasIndex("HorarioVersionId");

                    b.ToTable("PendientesGeneracion", "Horarios");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Periodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("PermitirExcepcionSemestre")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Semanas")
                        .HasColumnType("tinyint");

                    b.Property<bool>("SemestresPares")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .IsUnique()
                        .HasDatabaseName("UX_Periodos_UnicoActivo")
                        .HasFilter("[Estado] = 2 AND [Eliminado] = 0");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Periodos", "Academico");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.PeriodoCarrera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModalidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("ModalidadId");

                    b.HasIndex("PeriodoId", "CarreraId", "ModalidadId")
                        .IsUnique();

                    b.ToTable("PeriodosCarreras", "Academico");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Reticula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InicioVigencia")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasFilter("[Eliminado] = 0");

                    b.ToTable("Reticulas", "Catalogos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.RevisionHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HorarioVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HorarioVersionId");

                    b.ToTable("RevisionesHorario", "Gobierno");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.SesionHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Bloque")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("CargaAcademicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Dia")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DuracionBloques")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<Guid>("EspacioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaElimina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FijadaParaRegeneracion")
                        .HasColumnType("bit");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HorarioVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Origen")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UsuarioCrea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioElimina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CargaAcademicaId");

                    b.HasIndex("EspacioId");

                    b.HasIndex("HorarioVersionId", "Dia", "Bloque", "DocenteId")
                        .IsUnique();

                    b.HasIndex("HorarioVersionId", "Dia", "Bloque", "EspacioId")
                        .IsUnique();

                    b.HasIndex("HorarioVersionId", "Dia", "Bloque", "GrupoId")
                        .IsUnique();

                    b.ToTable("SesionesHorario", "Horarios");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.UsuarioCarrera", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "CarreraId");

                    b.HasIndex("CarreraId");

                    b.ToTable("UsuariosCarreras", "Seguridad");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Infrastructure.Identity.UsuarioAplicacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DebeCambiarContrasena")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Usuarios", "Seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Infrastructure.Identity.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Infrastructure.Identity.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Infrastructure.Identity.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Infrastructure.Identity.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.AjusteManual", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.SesionHorario", "SesionHorario")
                        .WithMany()
                        .HasForeignKey("SesionHorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SesionHorario");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.CargaAcademica", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.OfertaMateria", "OfertaMateria")
                        .WithMany()
                        .HasForeignKey("OfertaMateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("OfertaMateria");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.JornadaDocente", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.DisponibilidadDocente", "DisponibilidadDocente")
                        .WithMany("Jornadas")
                        .HasForeignKey("DisponibilidadDocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisponibilidadDocente");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.ConfiguracionSabatina", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.DisponibilidadBloque", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.DisponibilidadDocente", "DisponibilidadDocente")
                        .WithMany("Bloques")
                        .HasForeignKey("DisponibilidadDocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisponibilidadDocente");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.DisponibilidadDocente", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Docente", "Docente")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.DisponibilidadEspacio", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Espacio", "Espacio")
                        .WithMany()
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espacio");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.DocenteCarrera", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Docente", "Docente")
                        .WithMany("Carreras")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Espacio", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Carrera", "Carrera")
                        .WithMany("Espacios")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Grupo", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.PeriodoCarrera", "PeriodoCarrera")
                        .WithMany("Grupos")
                        .HasForeignKey("PeriodoCarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodoCarrera");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.HorarioVersion", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.PeriodoCarrera", "PeriodoCarrera")
                        .WithMany()
                        .HasForeignKey("PeriodoCarreraId");

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Periodo");

                    b.Navigation("PeriodoCarrera");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Materia", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Reticula", "Reticula")
                        .WithMany("Materias")
                        .HasForeignKey("ReticulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reticula");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.ModuloMateria", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.ModuloSabatino", "ModuloSabatino")
                        .WithMany("Materias")
                        .HasForeignKey("ModuloSabatinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.OfertaMateria", "OfertaMateria")
                        .WithMany()
                        .HasForeignKey("OfertaMateriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ModuloSabatino");

                    b.Navigation("OfertaMateria");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.ModuloSabatino", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.ConfiguracionSabatina", "ConfiguracionSabatina")
                        .WithMany("Modulos")
                        .HasForeignKey("ConfiguracionSabatinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionSabatina");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.OfertaMateria", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Oferta")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.PendienteGeneracion", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.CargaAcademica", "CargaAcademica")
                        .WithMany()
                        .HasForeignKey("CargaAcademicaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.HorarioVersion", "HorarioVersion")
                        .WithMany("Pendientes")
                        .HasForeignKey("HorarioVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargaAcademica");

                    b.Navigation("HorarioVersion");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.PeriodoCarrera", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Modalidad", "Modalidad")
                        .WithMany()
                        .HasForeignKey("ModalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Periodo", "Periodo")
                        .WithMany("Carreras")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Modalidad");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Reticula", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Carrera", "Carrera")
                        .WithMany("Reticulas")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.RevisionHorario", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.HorarioVersion", "HorarioVersion")
                        .WithMany()
                        .HasForeignKey("HorarioVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HorarioVersion");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.SesionHorario", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.CargaAcademica", "CargaAcademica")
                        .WithMany()
                        .HasForeignKey("CargaAcademicaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Espacio", "Espacio")
                        .WithMany()
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.HorarioVersion", "HorarioVersion")
                        .WithMany("Sesiones")
                        .HasForeignKey("HorarioVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargaAcademica");

                    b.Navigation("Espacio");

                    b.Navigation("HorarioVersion");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.UsuarioCarrera", b =>
                {
                    b.HasOne("TecAjalpan.Horarios.Domain.Entities.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TecAjalpan.Horarios.Infrastructure.Identity.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Carrera", b =>
                {
                    b.Navigation("Espacios");

                    b.Navigation("Reticulas");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.ConfiguracionSabatina", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.DisponibilidadDocente", b =>
                {
                    b.Navigation("Bloques");

                    b.Navigation("Jornadas");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Docente", b =>
                {
                    b.Navigation("Carreras");

                    b.Navigation("Disponibilidades");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.HorarioVersion", b =>
                {
                    b.Navigation("Pendientes");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.ModuloSabatino", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Periodo", b =>
                {
                    b.Navigation("Carreras");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.PeriodoCarrera", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("TecAjalpan.Horarios.Domain.Entities.Reticula", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
